version: '3.8'

services:
  mySql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: nolimit

    ports:
      - "3307:3306"


  dockertest_1:
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      - mySql

    ports:
      - "8081:8081"




